### PR TITLE
Updates as I reviewed.

### PR DESCRIPTION
**Pull request by rwjblue**
Feel free to take/leave any of these changes none of what you had was actually "wrong", I just think these updates make it more "right".

### CODE REVIEW

**Comment by stevekinney** [comment]
Thank you so much—I didn't realize I could omit the the initializer.

**Comment by rwjblue** [comment]
It is part of the `ember generate service` for ember-cli <= 0.1.5, but is removed from 0.2.0 (since you can use `Ember.inject.sevice()` without the initializer).

**Comment by stevekinney** [comment]
Hey @rwjblue, quick question to make sure I completely understand:

Since I have the `Ember.inject.service()` in the controller. I don't need the initializer. But if I didn't have the injection in the controller I would need to (or I could, rather) inject it with an initializer?

**Comment by rwjblue** [comment]
@stevekinney - Yes, that is true.  Having `foo: Ember.inject.service()` makes the `foo` service available on the object without an initializer.  If you injected it via an initializer it would work roughly the same, but be less declarative (IMHO) in the controller.

Also, the initializer that I removed here only injected into routes (and the service isn't used in a route that I could see), so it was just not used (in either case).

**Pull request merged**
